
type Props = {
    Action: number,
    Adventure: number,
    Animation: number,
    Comedy: number,
    Crime: number, 
    Documentary: number,
    Drama: number,
    Family: number,
    Fantasy: number,
    History: number,
    Horror: number,
    Music: number,
    Mystery: number,
    Romance: number,
    ScienceFiction: number,
    TVMovie: number,
    Thriller: number,
    War: number,
    Western: number,
}


export const CategoryIDs: Props = {
    Action: 28,
    Adventure: 12,
    Animation: 16,
    Comedy: 35,
    Crime: 80, 
    Documentary: 99,
    Drama: 18,
    Family: 10751,
    Fantasy: 14,
    History: 36,
    Horror: 27,
    Music: 10402,
    Mystery: 9648,
    Romance: 10749,
    ScienceFiction: 878,
    TVMovie: 10770,
    Thriller: 53,
    War: 10752,
    Western: 37,
}

